name: Start FoD Static Code Analysis

on: [workflow_dispatch]
#on:
#  push:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 4.2.x
      
      - name: Build Node.JS Application
        run: |
          npm install yo
          npm install bower gulp nodemon
          gulp build
      
      - name: Create Fortify on Demand Application Release
        id: creates_release
        # run: >
        #  token=$(
        #    curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' 
        #    --header 'Authorization: Bearer $FOD_AUTH_TOKEN' 
        #    -d '{
        #      "applicationId": $APPLICATION_ID,
        #      "releaseName": $RELEASE_NAME,
        #      "releaseDescription": $RELEASE_DESCRIPTION,
        #      "copyState": true,
        #      "copyStateReleaseId": $COPY_STATE_RELEASE_ID,
        #      "sdlcStatusType": "Production"
        #    }'
        #    'https://api.ams.fortify.com/api/v3/releases'
        #    | jq '.releaseId'
        #  )
        #  && echo "release_id=$token" >> "$GITHUB_OUTPUT"
        #  && echo ${{ env.release_id }}
        run: |-
          echo "release_id=$( curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer $FOD_AUTH_TOKEN' -d '{ "applicationId": $APPLICATION_ID , "releaseName": $RELEASE_NAME , "releaseDescription": $RELEASE_DESCRIPTION , "copyState": false, "sdlcStatusType": "Production" }' 'https://api.ams.fortify.com/api/v3/releases' | jq '.releaseId' )" "$GITHUB_OUTPUT"
        env:
          RELEASE_NAME: "Test_Game_Two"
          RELEASE_DESCRIPTION: "A sample pipeline that creates and configures an FoD release and begins a static scan."
          COPY_STATE_RELEASE_ID: 803401
          APPLICATION_ID: 154817
          FOD_AUTH_TOKEN: ${{ secrets.FOD_AUTH_TOKEN }}
          
      - name: Configure Static Scan for New Release
      - run: >
         curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json'
         --header 'Authorization: Bearer $FOD_AUTH_TOKEN' 
         -d '{ \ 
            "assessmentTypeId": 273, \ 
            "entitlementFrequencyType":"SingleScan", \ 
            "EntitlementId": 11948, \ 
            "technologyStackId": 16, \ 
            "performOpenSourceAnalysis": false, \ 
            "auditPreferenceType": "Automated", \ 
          }' 'https://api.ams.fortify.com/api/v3/releases/$RELEASE_ID/static-scans/scan-setup'
      - env:
          RELEASE_ID: ${{ steps.creates_release.outputs.release_id }}
          
      - name: Use Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Use Fortify ScanCentral Client for Packaging 
        uses: fortify/gha-setup-scancentral-client@v1
      - name: Use Fortify On Demand Uploader Utility
        uses: fortify/gha-setup-fod-uploader@v1
        
      - name: Package Application Code
        run: scancentral package -bt none -o package.zip
        
      - name: Upload Packaged Code and Begin Fortify Static Assessment
        run: java -jar $FOD_UPLOAD_JAR -z package.zip -aurl $FOD_AURL -purl $FOD_PURL -rid "$FOD_RELEASE_ID" -tc "$FOD_TENANT" -ac "$FOD_USER" "$FOD_PAT" -ep 2 -pp 1
        env:
          FOD_AURL: "https://api.ams.fortify.com/"
          FOD_PURL: "https://ams.fortify.com/"
          FOD_TENANT: "FranklinBank"
          FOD_USER: ${{ secrets.FOD_USER }}
          FOD_PAT: ${{ secrets.FOD_PAT }}
          FOD_APPLICATION_ID: 154817
          FOD_RELEASE_ID: ${{ steps.creates_release.outputs.release_id }}
