name: Start FoD Static Code Analysis

on: [workflow_dispatch]
#on:
#  push:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 4.2.x
      
     # - name: Build Node.JS Application
     #   run: |
     #     npm install yo
     #     npm install bower gulp nodemon
     #     gulp build
      
      - name: Create Fortify on Demand Application Release
        # run: >
        #  token=$(
        #    curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' 
        #    --header 'Authorization: Bearer <auth_token>' 
        #    -d '{
        #      "applicationId": <application_id>,
        #      "releaseName": <release_name>,
        #      "releaseDescription": <release_description>,
        #      "copyState": true,
        #      "copyStateReleaseId": <release_id_to_copy_state_from>,
        #      "sdlcStatusType": "Production"
        #    }'
        #    'https://api.ams.fortify.com/api/v3/releases'
        #    | jq '.releaseId'
        #  )
        #  && echo "release_id=$token" >> "$GITHUB_ENV"
        #  && echo ${{ env.release_id }}
        run: |
          token=$( curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer $FOD_AUTH_TOKEN' -d '{ "applicationId": $APPLICATION_ID , "releaseName": $RELEASE_NAME , "releaseDescription": $RELEASE_DESCRIPTION , "copyState": false, "sdlcStatusType": "Production" }' 'https://api.ams.fortify.com/api/v3/releases' | jq '.releaseId' )
          echo "release_id=$token" "$GITHUB_ENV"
          echo ${{ env.release_id }}
        env:
          RELEASE_NAME: "Test_Game_Two"
          RELEASE_DESCRIPTION: "A sample pipeline that creates and configures an FoD release and begins a static scan."
          COPY_STATE_RELEASE_ID: 803401
          APPLICATION_ID: 154817
          FOD_AUTH_TOKEN: ${{ secrets.FOD_AUTH_TOKEN }}
          
